exports_files([
    "defs.bzl",
    "py_pytest_test.bzl",
    "pytest_helper.py",
])

py_library(
    name = "pytest_helper",
    srcs = ["pytest_helper.py"],
    visibility = ["//visibility:public"],
)
