voices {
  voice_id: "Dilja"
  display_name: "Diljá"
  gender: FEMALE
  language_code: "is-IS"
  fs2melgan {
      alphabet: IPA
      fastspeech2_uri: "file:///models/dilja/fastspeech_jit.pt"
      melgan_uri: "file:///models/dilja/melgan_jit.pt"
      phonetizer_name: "phonetizer/is-IS/2021-07-26"
      normalizer_name: "default"
  }
}
voices {
  voice_id: "Alfur"
  display_name: "Álfur"
  gender: MALE
  language_code: "is-IS"
  fs2melgan {
      alphabet: IPA
      fastspeech2_uri: "file:///models/alfur/fastspeech_jit.pt"
      melgan_uri: "file:///models/alfur/melgan_jit.pt"
      phonetizer_name: "phonetizer/is-IS/2021-07-26"
      normalizer_name: "default"
  }
}
voices {
  voice_id: "Alfur_v2"
  display_name: "Álfur (v2)"
  gender: MALE
  language_code: "is-IS"
  espnet2 {
      alphabet: XSAMPA_WITH_STRESS_AND_SYLLABIFICATION
      model_pack_uri: "file:///models/alfur/espnet2.zip"
      vocoder_uri: "file:///models/universal/mbmelgan.zip"
      phonetizer_name: "phonetizer/ice-g2p"
      normalizer_name: "default"
  }
}
voices {
  voice_id: "Dilja_v2"
  display_name: "Diljá (v2)"
  gender: FEMALE
  language_code: "is-IS"
  espnet2 {
      alphabet: XSAMPA_WITH_STRESS_AND_SYLLABIFICATION
      model_pack_uri: "file:///models/dilja/espnet2.zip"
      vocoder_uri: "file:///models/universal/mbmelgan.zip"
      phonetizer_name: "phonetizer/ice-g2p"
      normalizer_name: "default"
  }
}
voices {
  voice_id: "Bjartur"
  display_name: "Bjartur"
  gender: MALE
  language_code: "is-IS"
  espnet2 {
      alphabet: XSAMPA_WITH_STRESS_AND_SYLLABIFICATION
      model_pack_uri: "zoo://espnet/GunnarThor_talromur_b_fastspeech2"
      vocoder_uri: "file:///models/universal/mbmelgan.zip"
      phonetizer_name: "phonetizer/ice-g2p"
      normalizer_name: "default"
  }
}
voices {
  voice_id: "Rosa"
  display_name: "Rósa"
  gender: FEMALE
  language_code: "is-IS"
  espnet2 {
      alphabet: XSAMPA_WITH_STRESS_AND_SYLLABIFICATION
      model_pack_uri: "zoo://espnet/GunnarThor_talromur_a_fastspeech2"
      vocoder_uri: "file:///models/universal/mbmelgan.zip"
      phonetizer_name: "phonetizer/ice-g2p"
      normalizer_name: "default"
  }
}
voices {
  voice_id: "Karl"
  display_name: "Karl"
  gender: MALE
  language_code: "is-IS"
  polly { }
}
voices {
  voice_id: "Dora"
  display_name: "Dóra"
  gender: FEMALE
  language_code: "is-IS"
  polly { }
}
phonetizers {
  name: "phonetizer/is-IS/2021-07-26"
  language_code: "is-IS"
  translators {
    lexicon {
      language_code: "is-IS"
      alphabet: XSAMPA
      uri: "file:///models/lexicon.txt"
    }
  }
  translators {
    sequitur {
      language_code: "is-IS"
      alphabet: IPA
      uri: "file:///models/sequitur.mdl"
    }
  }
  translators {
    sequitur {
      language_code: "is-IS"
      alphabet: IPA
      uri: "file:///models/sequitur_fail_en.mdl"
    }
  }
}
phonetizers {
  name: "phonetizer/ice-g2p"
  language_code: "is-IS"
  translators {
    lexicon {
      language_code: "is-IS"
      alphabet: XSAMPA
      uri: "file:///models/lexicon.txt"
    }
  }
  translators {
    ice_g2p {
      alphabet: XSAMPA_WITH_STRESS_AND_SYLLABIFICATION
    }
  }
}
normalizers {
  name: "default"
  grammatek {
    address: "grpc://localhost:8080"
  }
}
normalizers {
  name: "basic"
  basic { }
}